services:
  renovate:
    image: ghcr.io/renovatebot/renovate:44.65.5@sha256:4e10f76a79f1c597f427f83c788a9f5b14a6295784c4cb68307b89b0a954abce
    environment:
      GITHUB_COM_TOKEN: ${RENOVATE_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RENOVATE_CONFIG_FILE: /opt/renovate/config.json
      RENOVATE_DRY_RUN: ${RENOVATE_DRY_RUN:-full}
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES:-["zephyros-dev/media-server"]}
      RENOVATE_TOKEN: ${RENOVATE_TOKEN} # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
    privileged: true
    volumes:
      - ./config.json:/opt/renovate/config.json:ro
      # The .git-credentials file format can be found here:
      # https://git-scm.com/docs/git-credential-store#_storage_format
      - ./.decrypted.git-credentials:/home/ubuntu/.git-credentials:ro
      - ./.gitconfig:/home/ubuntu/.gitconfig:ro
