services:
  renovate:
    image: ghcr.io/renovatebot/renovate:44.83.0@sha256:91ace55cdb4df3c7c5928ac3d2f9c3e338a2bc2569563756fc98f678e1ec933f
    environment:
      GITHUB_COM_TOKEN: ${RENOVATE_TOKEN}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RENOVATE_CONFIG_FILE: /opt/renovate/config.json
      RENOVATE_DRY_RUN: ${RENOVATE_DRY_RUN:-full}
      RENOVATE_REPOSITORIES: ${RENOVATE_REPOSITORIES:-["zephyros-dev/media-server"]}
      RENOVATE_TOKEN: ${RENOVATE_TOKEN} # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
    privileged: true
    volumes:
      - ./config.json:/opt/renovate/config.json:ro
      # The .git-credentials file format can be found here:
      # https://git-scm.com/docs/git-credential-store#_storage_format
      - ./.decrypted.git-credentials:/home/ubuntu/.git-credentials:ro
      - ./.gitconfig:/home/ubuntu/.gitconfig:ro
