# Postgres version: https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres.yml
FROM docker.io/postgres:15-alpine@sha256:8f7d37ec5efca55c894112c9c2180ed5f389710b90510668d86f24a5095d7ff8
