# Postgres version: https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres.yml
FROM docker.io/postgres:15-alpine@sha256:287864e6428c1693bb792087a67a431e3e1470712e45771d47e6655213365ad9
