- name: Create ansible folder
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.config/ansible"
    state: directory
    mode: "0755"

- name: Setup ansible python requirements
  ansible.builtin.copy:
    src: ansible/requirements.txt
    mode: "0644"
    dest: "{{ ansible_facts.user_dir }}/.config/ansible/requirements.txt"

- name: Install ansible python requirements
  ansible.builtin.pip:
    requirements: "{{ ansible_facts.user_dir }}/.config/ansible/requirements.txt"
