- name: Misc settings
  tags: misc
  become: true
  block:
    - name: Enable SELinux
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    # Reference: https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    - name: Increase buffer size for HTTP/3 perfomance in caddy
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 7500000
        state: present
      loop:
        - net.core.rmem_max
        - net.core.wmem_max

    # Reference: https://jellyfin.org/docs/general/administration/troubleshooting.html#real-time-monitoring
    - name: Increase inotify watches for Jellyfin
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - name: fs.inotify.max_user_instances
          value: 512
        - name: fs.inotify.max_user_watches
          value: 524288

    - name: Add user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups:
          - libvirt
        append: true
