- name: Check if Snapper repo is installed
  ansible.builtin.stat:
    path: /etc/yum.repos.d/snapper.repo
  register: snapper_repo_state
- name: Install snapper repo
  when: not snapper_repo_state.stat.exists
  become: true
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/filesystems:snapper/Fedora_40/filesystems:snapper.repo
    dest: /etc/yum.repos.d/snapper.repo
    mode: "0600"

- name: Setup virtualization
  tags: virt
  become: true
  block:
    - name: Allow virt to use fuse.mergerfs
      ansible.posix.seboolean:
        name: virt_use_fusefs
        state: true
        persistent: true

# The os-prober takes a long time since we have large disks
- name: Disable os-prober
  become: true
  ansible.builtin.file:
    path: /etc/grub.d/30_os-prober
    mode: "0644"
    state: file

- name: Setup global packages
  become: true
  community.general.rpm_ostree_pkg:
    name:
      # Terminal tools
      - dua-cli
      - fd-find
      - fish
      # Server software
      - pip
      - power-profiles-daemon
      - restic
      - snapper
  register: rpm_ostree_pkg

- name: Reboot to apply rpm-ostree packages # noqa: no-handler
  become: true
  when: rpm_ostree_pkg.changed
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Setup podman
  tags: podman
  become: true
  vars:
    podman_config_dir_path: /etc/containers/containers.conf.d
  block:
    - name: Setup privileged ports for rootless podman
      ansible.posix.sysctl:
        name: net.ipv4.ip_unprivileged_port_start
        sysctl_set: true
        value: "80"

    - name: Setup podman configuration folder
      ansible.builtin.file:
        path: "{{ podman_config_dir_path }}"
        mode: "0755"
        state: directory

    - name: Setup podman configuration file root
      ansible.builtin.template:
        src: templates/podman/containers.conf.j2
        dest: "{{ podman_config_dir_path }}/containers.conf"
        mode: "0644"

- name: Setup rootless podman
  tags: podman
  vars:
    podman_config_dir_path: "{{ ansible_user_dir }}/.config/containers/containers.conf.d"
  block:
    - name: Enable podman socket
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        name: podman.socket
        scope: user
        state: started
    - name: Create containers config directory
      ansible.builtin.file:
        path: "{{ podman_config_dir_path }}"
        mode: "0755"
        state: directory
    - name: Setup podman configuration file user
      ansible.builtin.template:
        src: templates/podman/containers.conf.j2
        dest: "{{ podman_config_dir_path }}/containers.conf"
        mode: "0644"
    # https://github.com/containers/podman/issues/23515
    # This may be removed once podman is on version 5.2.2
    - name: Fix podman invalid volume
      when: ansible_hostname == "staging"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/containers/storage/volumes"
        mode: "0755"
        state: directory

- name: Setup low power mode
  become: true
  block:
    - name: Enable power-profiles-daemon
      ansible.builtin.systemd:
        name: power-profiles-daemon
        daemon_reload: true
        enabled: true
        state: started
    - name: Enable low power mode
      changed_when: false
      ansible.builtin.command:
        cmd: powerprofilesctl set power-saver

- name: Setup auto update
  become: true
  block:
    - name: Setup automatic update service
      ansible.builtin.systemd:
        name: rpm-ostreed-automatic.timer
        daemon_reload: true
        enabled: true
        state: started

- name: Enable cockpit
  become: true
  block:
    - name: Enable cockpit
      ansible.builtin.systemd:
        name: cockpit
        daemon_reload: true
        enabled: true
        state: started
