- name: Setup restic backup
  tags: restic
  become: true
  block:
    - name: Setup restic env
      community.general.ini_file:
        path: "{{ restic_env_path }}"
        section: null
        option: "{{ item.key }}"
        value: "{{ item.value }}"
        mode: "0600"
        no_extra_spaces: true
      loop: "{{ restic_env | dict2items }}"
      no_log: true
    # Comment this out for now since it takes too long to run
    - name: Check if restic repo exists
      block:
        - name: Check if restic repo exists
          changed_when: false
          ansible.builtin.command:
            cmd: restic cat config
          environment: "{{ restic_env }}"
          register: restic_repo_status
      rescue:
        - name: Init restic repo
          ansible.builtin.command:
            cmd: restic init
          environment: "{{ restic_env }}"
          when: >-
            "bucket not found" in restic_repo_status.stderr
            or "Is there a repository at the following location" in restic_repo_status.stderr
          changed_when: false
        - name: Unlock restic repo
          ansible.builtin.command:
            cmd: restic unlock
          environment: "{{ restic_env }}"
          when: '"unable to create lock in backend" in restic_repo_status.stderr'
          changed_when: false
    - name: Setup restic exclude file
      ansible.builtin.template:
        src: restic/exclude.j2
        dest: "{{ restic_env.EXCLUDE_FILE }}"
        mode: "0644"
    - name: Setup restic systemd
      ansible.builtin.template:
        src: restic/{{ item }}.service.j2
        dest: /etc/systemd/system/{{ item }}.service
        mode: "0644"
      loop:
        - restic-backup
        - restic-prune
        - restic-unlock # This service can be used manually to unlock the repo
    - name: Setup restic timer
      ansible.builtin.include_role:
        name: systemd_timer
      vars:
        systemd_timer_name: "{{ item.name }}"
        systemd_timer_become: true
        systemd_timer_schedule: "{{ item.schedule }}"
      loop:
        - name: restic-backup
          schedule: "23:00:00"
        - name: restic-prune
          schedule: "Wed 8:00:00"
