collections:
  - name: ansible.posix
    version: 2.0.0
  - name: community.libvirt
    version: 1.3.1
  - name: containers.podman
    version: 1.16.3
  - name: devsec.hardening
    version: 10.2.0
  - name: sdorra.porkbun
    version: 1.0.1
roles:
  - name: aisbergg.snapper
    version: v2.1.0
