collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.3.0
  - name: community.libvirt
    version: 2.0.0
  - name: containers.podman
    version: 1.19.0
  - name: devsec.hardening
    version: 10.5.0
  - name: sdorra.porkbun
    version: 1.0.1
roles:
  - name: aisbergg.snapper
    version: v2.1.0
