collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.libvirt
    version: 1.3.0
  - name: containers.podman
    version: 1.11.0
  - name: devsec.hardening
    version: 9.0.1
roles:
  - name: aisbergg.snapper
    version: v2.1.0
