- name: Setup variable for user scope {{ systemd_timer_name }}
  ansible.builtin.set_fact:
    systemd_timer_path: "{{ ansible_user_dir }}/.config/systemd/user/{{ systemd_timer_name }}.timer"
    systemd_timer_scope: user
  when: not systemd_timer_become

- name: Setup variable for system scope {{ systemd_timer_name }}
  ansible.builtin.set_fact:
    systemd_timer_path: /etc/systemd/system/{{ systemd_timer_name }}.timer
    systemd_timer_scope: system
  when: systemd_timer_become

- name: Setup systemd with scope {{ systemd_timer_name }}
  module_defaults:
    ansible.builtin.systemd:
      daemon_reload: true
      name: "{{ systemd_timer_name }}.timer"
      scope: "{{ systemd_timer_scope }}"
  become: "{{ systemd_timer_become }}"
  block:
    - name: Remove systemd timer {{ systemd_timer_name }}
      when: systemd_timer_state == "absent"
      block:
        - name: Check if service exists {{ systemd_timer_name }}
          ansible.builtin.stat:
            path: "{{ systemd_timer_path }}"
          register: systemd_timer_file

        - name: Stop systemd timer {{ systemd_timer_name }} # noqa: args[module]
          ansible.builtin.systemd:
            enabled: false
            state: stopped
          when: systemd_timer_file.stat.exists

        - name: Remove systemd timer file {{ systemd_timer_name }}
          ansible.builtin.file:
            path: "{{ systemd_timer_path }}"
            state: absent

    - name: Set systemd timer state {{ systemd_timer_name }}
      when: systemd_timer_state == "started" or systemd_timer_state == "stopped"
      block:
        - name: Template systemd timer {{ systemd_timer_name }}
          ansible.builtin.template:
            src: template.timer.j2
            dest: "{{ systemd_timer_path }}"
            mode: "0600"
          register: systemd_timer_file_state

        - name: Restart systemd timer if changed {{ systemd_timer_name }} # noqa: no-handler
          ansible.builtin.set_fact:
            systemd_timer_final_state: restarted
          when:
            - systemd_timer_file_state.changed
            - systemd_timer_state != "stopped"

        - name: Set systemd timer state {{ systemd_timer_name }} # noqa: no-handler
          ansible.builtin.set_fact:
            systemd_timer_final_state: "{{ systemd_timer_state }}"
          when: not systemd_timer_file_state.changed

        - name: Set systemd timer state {{ systemd_timer_final_state + ' ' + systemd_timer_name }} # noqa: args[module]
          ansible.builtin.systemd:
            enabled: true
            state: "{{ systemd_timer_final_state }}"
