FROM docker.io/caddy:2.8.4-builder-alpine@sha256:f90427c3bac00df769e119901760ed97b5e55742f8b646df9fe171cf7dbff287 AS builder

RUN --mount=type=cache,target=/go/pkg,sharing=locked \
    xcaddy build \
    --with github.com/caddy-dns/dynv6

FROM docker.io/caddy:2.8.4-alpine@sha256:221bcf3be161b0d856bdb7bea76b42386d732d19348f79692404829532d83f4a

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
