FROM docker.io/caddy:2.7.6-builder@sha256:465ccdb757e5a2b6d79750e8332217bc942c84ae7ed732ebcf913d6607474ccd AS builder

RUN --mount=type=cache,target=/go/pkg,sharing=locked \
    xcaddy build \
    --with github.com/caddy-dns/dynv6

FROM docker.io/caddy:2.7.6-alpine@sha256:b54e13f28b3e5e38aba46aa2fb7253227b9aa12b282a8bef4a5efa24e8c9abab

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
