# Version 3.1.2 broken atm https://github.com/Lissy93/dashy/issues/1935
FROM ghcr.io/lissy93/dashy:4.0.6@sha256:53c178823650effa3ca6bf37aab2c903ec0e2c18a7cbded3894f2412b71226cf
RUN chown -R node:node /app
USER node
RUN mkdir -p /app/dist
