# Version 3.1.2 broken atm https://github.com/Lissy93/dashy/issues/1935
FROM ghcr.io/lissy93/dashy:4.0.2@sha256:e12a72ed61b5529bfd133832a36f40c13b04c70da786be04624bbe42d36adf11
RUN chown -R node:node /app
USER node
RUN mkdir -p /app/dist
