# Version 3.1.2 broken atm https://github.com/Lissy93/dashy/issues/1935
FROM ghcr.io/lissy93/dashy:3.1.9@sha256:fcab1d29176c51b176a00c9c903ed20dfa7dd4abc370d02ffc77f50864188d88
RUN chown -R node:node /app
USER node
RUN mkdir -p /app/dist
