# https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst
FROM docker.io/postgres:18-alpine@sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40
