# https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst
FROM docker.io/postgres:17-alpine@sha256:0bcc5bbbb2aa9c9b4c6505845918c7eb55d783cf5c1f434fac33012579fb149d
