# https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst
FROM docker.io/postgres:17-alpine@sha256:660ca1afcda0de964eeb2557a5d287d656a8ec1bb97e98fe7a1c3da203d88a12
