# Postgres version: https://github.com/immich-app/immich/blob/main/docker/docker-compose.prod.yml
FROM docker.io/postgres:15-alpine@sha256:8307d52141c90c1de96f0d31ec7583a819a07de66d2bc5ff1fd3bff1885eac93
