# Postgres version: https://github.com/immich-app/immich/blob/main/docker/docker-compose.prod.yml
FROM docker.io/postgres:15-alpine@sha256:d4c84dd76d80c7ad3189d5367112ac196d82d11472f21b0246a19e75411574a2
