# Postgres version: https://github.com/immich-app/immich/blob/main/docker/docker-compose.prod.yml
FROM ghcr.io/immich-app/postgres:18-vectorchord1.1.1@sha256:a20e21841b21b9c009daf572c844ffedfaef75fce51287bbf080edf171ef0834
