# Postgres version: https://github.com/immich-app/immich/blob/main/docker/docker-compose.prod.yml
FROM ghcr.io/immich-app/postgres:18-vectorchord1.1.1@sha256:4303394b926b7b7af5d4d15a6372c3cfff4ee994a4cf32c5479aa5ef73972077
