FROM ghcr.io/paperless-ngx/paperless-ngx:2.13.5@sha256:199c67ed55bfb9d58bf90db2ee280880ae9ebc63413e54c73522f9c4ebdc7bad
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# The entrypoint script cannot be sourced so we have to write our own tesseract language installation
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh
ARG INSTALL_LANGUAGE
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update \
    && apt install -y --no-install-recommends \
    tesseract-ocr-$INSTALL_LANGUAGE
