FROM ghcr.io/paperless-ngx/paperless-ngx:2.20.14@sha256:b89f83345532cfba72690185257eb6c4f92fc2a782332a42abe19c07b7a6595f
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# The entrypoint script cannot be sourced so we have to write our own tesseract language installation
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh
ARG INSTALL_LANGUAGE
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update \
    && apt install -y --no-install-recommends \
    tesseract-ocr-$INSTALL_LANGUAGE
