FROM ghcr.io/paperless-ngx/paperless-ngx:2.18.1@sha256:2dbee2d7fea624af8f12877936f6d728f351d2b8f4ddb34bdc06d933f0f47200
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# The entrypoint script cannot be sourced so we have to write our own tesseract language installation
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh
ARG INSTALL_LANGUAGE
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update \
    && apt install -y --no-install-recommends \
    tesseract-ocr-$INSTALL_LANGUAGE
