FROM docker.io/caddy:2.7.6-builder-alpine@sha256:8024044c8b2ad1770b7d4fd63fcea778ae0b52662801f77ffc51ff5029f6845f AS builder

# Using specific build version until caddy release a new version: https://github.com/caddyserver/caddy/issues/6209
RUN --mount=type=cache,target=/go/pkg,sharing=locked \
    xcaddy build e1f4b83ffaa861e8f383ba52108e6449b53217f2 \
    --with github.com/caddy-dns/dynv6 \
    --with github.com/mholt/caddy-dynamicdns

FROM docker.io/caddy:2.7.6-alpine@sha256:b54e13f28b3e5e38aba46aa2fb7253227b9aa12b282a8bef4a5efa24e8c9abab

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
