FROM docker.io/caddy:2.7.6-builder-alpine@sha256:481c3357e533d892e2621d69ce3747a459e40af2f56159bcbd64b38bee1aa5bd AS builder

# Using specific build version until caddy release a new version: https://github.com/caddyserver/caddy/issues/6209
RUN --mount=type=cache,target=/go/pkg,sharing=locked \
    xcaddy build e1f4b83ffaa861e8f383ba52108e6449b53217f2 \
    --with github.com/caddy-dns/dynv6 \
    --with github.com/mholt/caddy-dynamicdns

FROM docker.io/caddy:2.7.6-alpine@sha256:b3af2274b3e1ab8bbe0ceee5882f88c32afa1b1852afa7fef91524ad28469d1a

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
