config:
    MODE_FILTER: ENC[AES256_GCM,data:FIc7m3KG9DXy6fu6,iv:PGN+sqJP4Llk3LYiSO2JB83YKugYG3/wp0uH71BiA/w=,tag:6dOWp1GQNTULk5+CTbBBGg==,type:str]
    FLOWOFFLOAD: ENC[AES256_GCM,data:LcmSpV0L4ao=,iv:6cCHcnLQaMRZ7HdFDfCbv9E42KW2EjjJJjal35QD1Po=,tag:fbl05z0KDrzkyoT56fAWLA==,type:str]
    NFQWS2_ENABLE: ENC[AES256_GCM,data:sw==,iv:oI0APu0PmeXNBINRRhvwzx77/SuCGJzFOSOxj5epC8I=,tag:5q4JdaJaXeRuOlkPydXSKw==,type:str]
router_list:
    - ENC[AES256_GCM,data:WPMddjm7PYZjxFg8p0gf,iv:GLU+eflNVw0E+6YoCfz8trZ355xFMS+rNteu12limI4=,tag:oSuu8lBCINV8r+YVDxnTGA==,type:str]
custom_user_include: ENC[AES256_GCM,data:AhHkWscLAMg=,iv:F98pOJayIjZGWJlO5BOcbPx2eR06uhFjrZ8Cg1p7FtE=,tag:1Fe2EyiN1M275zDt2UTTFw==,type:str]
sops:
    age:
        - recipient: age19ycrg4v57swrmzsuffwxlrw7ld26wfttxag3r7qwqq4jaatdeeeq9kmsu2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZFBaM1M0REt1WGFlSGxN
            S0lXQ0laaGdpaXR4YnQ3UHU4SmdtcUVpWUVjClh0VTlFQVg3bFF5NzFhMlhVVWZL
            ODRpWjZTVk5JQjFiSVRTQm5SUGU0b1UKLS0tIFZ3ak9TRHowMGhPMFRSVC9ad3pk
            aTdoVjkwMHFPVWVQeklHZE9sd3pMRjAKt6hgPodrGEgIZnW5B/BhtjMAl2d4MANv
            Ie2CQ3osLO7bwUFU9lfzk4CvEnACBZPDnVm+0L8+HdPGr1UZ6fpzMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T09:13:12Z"
    mac: ENC[AES256_GCM,data:sKIWwICbz2u1W2GLHWgXoNyVm3wjTsCgTUvXPCawdQNQVxgLTJULppYI25ZICeF+u3lU5PYJyyONIcP2XIzE68uIw0Xt3EguPZAHbC1MIBUSAAbSy6Ttr9qHu1LF7kRNKa3tnTh+sQKO5UYX9JF0BJnrniI+b58M2giu1QnB3Lg=,iv:ib3vdgp7MFt3md2467J8Y5sjKA7LJzSDCxmRf+INc5U=,tag:j+sUoqTI1jlZLG/cJ8YWOA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
