FROM ghcr.io/paperless-ngx/paperless-ngx:2.12.0@sha256:7a1d34bfaba5243aa4398d3b8abadc7234b6aa844837b329d598bed5ca17a0a9
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# The entrypoint script cannot be sourced so we have to write our own tesseract language installation
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh
ARG INSTALL_LANGUAGE
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update \
    && apt install -y --no-install-recommends \
    tesseract-ocr-$INSTALL_LANGUAGE
