FROM ghcr.io/paperless-ngx/paperless-ngx:2.11.6@sha256:fca12ddea5509819dd0702cf128944aa23d01dd850a2536a96c2b46fb982b9bb
RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache
# The entrypoint script cannot be sourced so we have to write our own tesseract language installation
# https://github.com/paperless-ngx/paperless-ngx/blob/main/docker/docker-entrypoint.sh
ARG INSTALL_LANGUAGE
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt update \
    && apt install -y --no-install-recommends \
    tesseract-ocr-$INSTALL_LANGUAGE
