# https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres.yml
FROM docker.io/postgres:17-alpine@sha256:7da46003709776fe15fcac73a7c961e0ad820e4a526a784ca29e656948a94ecf
