- name: Gather host facts
  tags: always
  block:
    - name: Check if nvidia is installed
      changed_when: false
      ansible.builtin.stat:
        path: /usr/bin/nvidia-smi
      register: nvidia_smi
    - name: Set nvidia installed fact
      ansible.builtin.set_fact:
        nvidia_installed: "{{ nvidia_smi.stat.exists }}"
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html

- name: Generate facts
  delegate_to: localhost
  tags: always
  module_defaults:
    ansible.builtin.command:
      chdir: cue
    ansible.builtin.copy:
      mode: "0600"
      dest: cue/tmp/fact.json
  block:
    - name: Create tmp cue folder
      ansible.builtin.file:
        path: cue/tmp
        state: directory
        mode: "0755"
    - name: Export facts to file # noqa: args[module], risky-file-permissions
      changed_when: false
      vars:
        caddyfile_content: ""
      ansible.builtin.copy:
        content: "{{ lookup('vars', 'vars') | to_nice_json }}"
    - name: Get container cue facts
      changed_when: false
      ansible.builtin.command:
        cmd: cue export --out json
      register: cue_facts
    - name: Get caddyfile content
      vars:
        application: "{{ cue_facts.stdout | from_json | json_query('application') }}"
      ansible.builtin.set_fact:
        caddyfile_content: "{{ lookup('ansible.builtin.template', 'roles/application/templates/caddy/Caddyfile.j2') }}"
    - name: Export facts to file # noqa: args[module], risky-file-permissions
      changed_when: false
      ansible.builtin.copy:
        content: "{{ lookup('vars', 'vars') | to_nice_json }}"
    - name: Re-get container cue facts with caddyfile content
      changed_when: false
      ansible.builtin.command:
        cmd: cue export --out json
      register: cue_facts
    - name: Set cue facts
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ cue_facts.stdout | from_json | dict2items }}"
      no_log: true
