- name: Gather host facts
  tags: always
  block:
    - name: Check if nvidia is installed
      block:
        - name: Run nvidia-smi
          changed_when: false
          ansible.builtin.command:
            cmd: /usr/bin/nvidia-smi
          register: nvidia_smi
        - name: Set nvidia installed fact
          ansible.builtin.set_fact:
            nvidia_installed: true
      rescue:
        - name: Nvidia is not installed
          ansible.builtin.set_fact:
            nvidia_installed: false
    # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html

- name: Generate facts
  delegate_to: localhost
  tags: always
  module_defaults:
    ansible.builtin.command:
      chdir: cue
  vars:
    caddyfile_content: ""
    fact_var_names: "{{ query('ansible.builtin.varnames', '^[^_].*') | difference(['vars', 'fact_var_names', 'fact_json', 'ansible_delegated_vars']) | list }}"
    fact_json: "{{ dict(fact_var_names | zip(query('ansible.builtin.vars', *fact_var_names))) | to_nice_json }}"
  block:
    - name: Get container cue facts # noqa: args[module]
      changed_when: false
      ansible.builtin.command:
        cmd: 'cue export . -l ''"factEmbed"'' json: - --out json'
        stdin: "{{ fact_json }}"
      register: cue_facts
    - name: Get caddyfile content
      vars:
        application: "{{ cue_facts.stdout | from_json | json_query('application') }}"
      ansible.builtin.set_fact:
        caddyfile_content: "{{ lookup('ansible.builtin.template', 'roles/application/templates/caddy/Caddyfile.j2') }}"
    - name: Re-get container cue facts with caddyfile content # noqa: args[module]
      changed_when: false
      ansible.builtin.command:
        cmd: 'cue export . -l ''"factEmbed"'' json: - --out json'
        stdin: "{{ fact_json }}"
      register: cue_facts
    - name: Dump cue facts to file for debugging # noqa: args[module], risky-file-permissions
      when: cue_fact_debug | default(false)
      ansible.builtin.copy:
        content: "{{ fact_json }}"
        dest: cue/tmp/fact.json
        mode: "0600"
    - name: Set cue facts
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: "{{ cue_facts.stdout | from_json | dict2items | rejectattr('key', 'equalto', 'factEmbed') }}"
      no_log: true
