#!/usr/bin/env bash
#MISE description="Run the ansible deployment playbook against the server"
set -euo pipefail

eval $(ssh-agent)
sops -d secret/deployment/ssh_key.sops | ssh-add - &> /dev/null
export ANSIBLE_CALLBACKS_ENABLED="timer"
export ANSIBLE_DISPLAY_SKIPPED_HOSTS="False"
export ANSIBLE_STDOUT_CALLBACK="dense"
export ANSIBLE_HOST_KEY_CHECKING="False"
uv run ansible-playbook main.yaml
