# Postgres version: https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/system_requirements.rst
FROM docker.io/postgres:15-alpine@sha256:0b5b578c2cfe57ca4de7e53bf800051c605e5aad17b2dac47128cc9b52e11704
